### ISSUE TITLE
will you apply it on TF2

### ISSUE THREAD

**Issue by manhlab** [Shaoli-Huang/SnapMix#1]
That's interesting to implement and apply it on Tensorflow 2

**Comment by Shaoli-Huang** [comment]
Hi, currently, I did not have a plan to make an implementation based on TF2.
 If you have worked out the TF2 version and reproduce the results, please let me know. I would share your repo as an extra link of implementation.

**Comment by mithils3** [comment]
@Shaoli-Huang  a tf2 implementation is here https://github.com/wangermeng2021/SnapMix-tensorflow2 please link it in the repo
