### ISSUE TITLE
老哥我看你是中国人我就冒昧的用中文向你提问了

### ISSUE THREAD

**Issue by dpxudong** [Shaoli-Huang/SnapMix#6]

**Comment by dpxudong** [comment]
在我实现snapmix的过程中我遇到了如下几个问题首先是在get_spm函数那里我看你在做归一化的过程中是
```
        for i in range(bs):
            outmaps[i] -= outmaps[i].min()
            outmaps[i] /= outmaps[i].sum()``
```
我对这个代码的理解是你对输出的先减去最小值然后求平均做一个归一化，但是我在debug的过程中发现减去最小值 在除以他们的和 整个outmap最后都是0，我也不知道为什么，我试过更换模型，换训练好的模型来做这个方法，但是还是不行。
第二个就是在snapmix的主函数中
```
            lam = 1 - ((bbx2 - bbx1) * (bby2 - bby1) / (input.size()[-1] * input.size()[-2]))
            lam_a[torch.isnan(lam_a)] = lam
            lam_b[torch.isnan(lam_b)] = 1-lam
```
这是你的代码88-90行的部分 我看之前的部分是按照论文求的a,b标签，但是你这个代码一加显然就不是论文中求取标签的方式了，我也试过把这三行代码去掉并且把get_spm函数中的求归一化的代码采用softmix进行归一化，我以为我这样做更符合论文的做法，但是在我实验的过程中训练会出现梯度爆炸，希望老哥可以解答一下，谢谢了，你的论文写的非常好。

**Comment by Shaoli-Huang** [comment]
"但是我在debug的过程中发现减去最小值 在除以他们的和 整个outmap最后都是0，我也不知道为什么"
请问你是用这个代码出现的这个问题吗？ 我尝试了下，并未出现这种状况，如果你是自己实现的代码，我觉得你可以debug下，outmap做normalization前后的值是否有异常。

关于代码88-90行的部分，那是考虑在极个别情况随机的区域比较小，而且该区域对应SPM的区域的值全是0的情况，这样的话，除去他们的sum就会出现NAN的情况。这时候，我是采用了cutmix使用面积比方式来计算标签比例。

**Comment by dpxudong** [comment]
谢谢你的回答老哥
